### ISSUE TITLE
Repose adjustments

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#1]
Assuming it stays:

Adjustments to natural stone list.
1. Rustic: slate. others?
1. Earthworks: chalk, slate, ?
1. Chisel: limestone, marble, ?
1. Quark: marble, limestone, basalt, ?

**Comment by gchpaco** [comment]
Chisel also has a basalt, which spawns near lava chunks.  Those are all the ones I really remember.

**Comment by esotericist** [comment]
I haven't gotten to adding the additional stones yet, but I did turn off avalanches, to minimize certain kinds of problems.

**Comment by esotericist** [comment]
configuration problems solved by way of removing the mod.

Too many unresolvable problems.
