### ISSUE TITLE
Possible Extra Utilities 2 Removal

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#16]
Things we lose that we need to determine replacements for:

* Compressed Cobble (maybe sand, gravel, and netherrack?)
* Golden Lasso
* Redstone clock (I believe we had something for this, but it's possible one of the redstone mod removals cost us that)
* Trash Can (Thermal Expansion Nullifer can do the job, but poss. too expensive)
* Mechanical User
* Angel Block (there's a scaffolds mod in sevtech that might help)
* Drums (Rustic provides solid entry level portable fluid, TE has mid-grade. Blood Magic provides the portable tanks to end all portable tanks. Any holes?)

**Comment by gchpaco** [comment]
The drums we're probably sufficient on.  Many Mechanical User applications can be done by Gadgetry or the Botaunomy mod's addition to livingwood avatars, but I'm not sure if they can use tools.  Golden lassos hurt.

**Comment by gchpaco** [comment]
N.B.: golden lassos can maybe be worked around with morbs from TE (single use or maybe sort of reusable "pick up a mob and do things with it").

**Comment by gchpaco** [comment]
We've pulled this.  Closing.
