### ISSUE TITLE
Thaumcraft 6 inclusion

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#18]
Things must be cut. #16 discusses the biggest mod we can just outright remove, but it only accounts for less than half of the required block IDs.

Our best possible victim after that is Quark. In part, though, rather than in whole.

Proposed deletions:
* colored flower pots (16 IDs; I don't think I've ever actually wanted one of these)
* stained planks (~49 IDs including slabs and stairs; apparently rustic also adds these)
* stained clay tiles (~50 IDs including slabs and stairs; they're pretty, but possibly unnecessary)

If necessary, there's probably smaller things we can drop if we want to maintain one of those.

**Comment by gchpaco** [comment]
I've never wanted a colored flower pot, and I generally don't benefit from the stained planks; didn't use them in Rustic, either.

Stained clay tiles *are* useful for roofing sometimes.  We could probably still remove them, but it's a little less cut and dried for me.

**Comment by gchpaco** [comment]
We've managed to cram TC6 in and discarded the colored flower pots, so I'm closing this.
