### ISSUE TITLE
VFP Mod Integration

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#2]
Chili peppers should be in kebabFill in addition to kebabMain.

Any other rustic foods not completely filled in?

**Comment by esotericist** [comment]
@gchpaco  For that matter, do we have any foods in general from recent mod updates/additions that need integrating?

Dare we go down the road of integrating twilight forest with VFP?

**Comment by gchpaco** [comment]
Integrating TF with VFP is superficially somewhat easy until you get into exotica; the venison, for example, works fine as an `ingredientKebabAdventure`.  Meef and Meef Steak are probably close enough to `foodGoodMeat` and probably `ingredientKebabAdventure`, `foodRedMeat` and kin too.

Minor omissions: ActAdd seeds should be `itemDryableSeed`.  Arguably so should roots herb seeds.  A curious lacunae in VFP is that compacted seeds can only be wheat seeds; not even beetroot.  I don't see any particularly good reason for that to be the case.

One thing we should think about before jumping on is ActAdd rice.  The rice bread could be `foodBread`.

**Comment by esotericist** [comment]
Regarding `itemDryableSeed`, ALL actadd and roots seeds? I remember before it was a bounded list. I don't remember why, but you thought, for instance, only tomato seed needed to be in that list before, from rustic, despite there being other seeds.

Why is there hesitation on classifying rice bread as foodBread?

**Comment by gchpaco** [comment]
I remember having this discussion and I don't remember why I thought that.  What are dryable seeds used for, again?  Compacted seeds should definitely be more than just wheat seeds; that's turned into seed oil, and for the purposes of VFP seed oil there should be no particular problem in every seed in the game being VFP seed oil-able.  (It's not cross compatible with Forestry or IE seed oil, anyway, I don't think.)

My hesitation on classifying rice bread as `foodBread` was mostly because it's so easy to make lots of rice, and the rice -> rice bread recipe is quite convenient and relatively inexpensive.  But that same thing is true of vanilla wheat, so I no longer think there's any reason to hold off on rice bread being `foodBread`.

**Comment by esotericist** [comment]
dryable seeds are used primarily for drying agent, I believe.

**Comment by esotericist** [comment]
Took another look at things, and: `itemDryableSeed` is used only for the Dried Seeds item, which in turn is used in the creation of Leavening Agent, Enzyme Extraction Agent, and Unprocessed Drying Agent.

To be clear: these actually use the `additiveScaffold` oredict, which contains dried seeds, and wheat/melon/pumpkin seeds. As far as I know those three recipes are the only ones to use `additiveScaffold`.

Something else adds these:
`listAllmeatcooked`. (contains cooked porkchop, cooked fish, cooked salmon, steak, cooked chicken, cooked rabbit, cooked mutton, cooked buffalo)
`listAllmeatraw`, `listAllbeefraw`, `listAllbuffaloraw`. Contains only raw buffalo meat (from totemic). `listAllbeefraw` does not contain raw beef!
`istAllbeefcooked`. Contains steak and cooked buffalo.
`listAllbuffalocooked`. contains only cooked buffalo.

`listAllfruit`. Contains from BOP: pear, peach, persimmon. Contains from Rustic: olives, ironberries, grapes.
`listAllberry`. Contains from rustic: olives, ironberries, grapes.

Do we care about these lists? Are they USEFUL for anything at all? they aren't structured like VFP oredicts, and since some of them only contain bop/rustic/totemic bits, I have NO IDEA what adds them.

**Comment by esotericist** [comment]
For actual changes:

TF venison and meef: I gave both to `foodGoodMeat`, `foodRedMeat`, `ingredientKebabAdventure` (these are the same ones horse has)
venison and meef steak: `foodGoodMeatCooked` and `foodRedMeatCooked`

Interesting discovery in VFP: 
`foodNativeGameCooked`. Steak, Cooked Rabbit, Cooked Mutton, and Cooked Bear are the entries. Tentatively adding cooked venison to that list.

chili peppers added to `kebabFill`, rice bread added to `foodBread`. 

Added a recipe for compacted seeds that uses `listAllseed`.

These changes have been pushed, but I'm not closing it yet since we're still feeling out the weirdnesses.

**Comment by esotericist** [comment]
Copied the contents of `listAllseed` to `itemDryableSeed`.

This covers our outstanding integration things. As usual, reopen issue if something new is discovered.

**Comment by gchpaco** [comment]
You added `foodBread` to actadd rice bread, which is great, but `bread` and `foodBreadSandwich` are the ones used by VFP, it appears. VFP itself is not consistent about assigning `foodBreadSandwich` to some of its breads for reasons I don't really understand, but I think we probably ought to.  Serves the original goal of making rice bread useful for more than just itself.

**Comment by esotericist** [comment]
Okay. Easy enough.

**Comment by esotericist** [comment]
Looking at it more closely, the only oredict for bread that VFP visibly uses is `foodBreadSandwich`. It doesn't claim to use `bread` or `foodBread` for anything, and the bit o' bread recipe doesn't use an oredict; those are individual recipes (so we should probably make one for rice).

Straight up swapping the `foodBread` oredict on rice bread for `foodBreadSandwich` since all evidence implies the former (and `bread` as well) is irrelevant.

For the bit o' bread recipe, output seems to vary based on input:

Vanilla bread: 3 bits.
french bread: 4 bits.
enriched bread: 5 bits.
egg bread, potato bread: 9 bits.

pumpkin, apple, molasses, and muscle breads are not permitted to make bit o' bread for unclear reasons.

Given the nature of rice bread, 3 bits seems appropriate, assuming I can get the CT recipe to work with the cutter?

**Comment by gchpaco** [comment]
We've got this stuff largely integrated, so closing this ticket.
