### ISSUE TITLE
Elucent Eviction

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#20]
Because Elucent insists on being a drama queen and has yanked source for his mods, Roots 2 and Gadgetry need to go.

For the time being, Embers is being kept, due to it providing some incomparables and the fact someone (soot dev) is keeping it functional.

Things dropping Roots costs us:
Wooden shears: fixable with a [mod addition](https://minecraft.curseforge.com/projects/sbm-wooden-shears).
Thatch: workaroundable by making an alternate recipe for the Betweenlands thatch block. Current proposal: sugar cane and maybe string?
Shatter spell: can be worked around, just highly unfortunate.

Things dropping Gadgetry costs us:
Remote block breaker: There's no direct equivalent to this, but more to the point, its breaker has some filtering we can't trivially replace. At least there's some filtering tricks with Progressive Automation that are pertinent.
Remote block placer: Botania can do this for us, albeit with caveats.
Remote block clicker: We're short on general purpose clicking blocks. Ironically, this may require us to bring back Extra Utilities 2.

Anything else?

**Comment by gchpaco** [comment]
N.B.: Another thing I use from roots that affects tiering of charcoal pits from Forestry is the firestarter.  Less critical than the shears, tho.

**Comment by gchpaco** [comment]
Since EpicSquid has picked up all of Elucent's old mods, we've re-added roots.  Gadgetry is still out for the moment.
