### ISSUE TITLE
Akashic Tome integration

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#5]
Integrated Dynamics' book doesn't want to go in the damn thing.
bibliocraft might also be fussy about it.

**Comment by gchpaco** [comment]
Book is called "On the Dynamics of Integration".

**Comment by esotericist** [comment]
So what on earth do we use as a keyword for bibliocraft?

**Comment by gchpaco** [comment]
IDK. "dynamics", maybe, and just trust us to be reasonable about it.

**Comment by esotericist** [comment]
Done and synced to dropbox.
