### ISSUE TITLE
Akashic Tome integrated crafting recipe

### ISSUE THREAD

**Issue by gchpaco** [gchpaco/minecraft_eso_paco#7]
Inspired by https://twitter.com/Vazkii/status/926114034742648832

Things that should be in there:
- Roots herblore
- Roots spellcraft?
- Rustic book (Almanac)
- ActAdd book
- ExU 2 book
- Modular Routers book
- IE book
- Magneticraft book
- Food Journal
- Deep Resonance manual
- RFTools manual
- RFTools control manual
- RFTools dimensions manual
- TIS-3d manual
- XNet manual

Things we start with that should maybe get integrated?:
- Tinkers
- Integrated Dynamics book
- Astral Sorcery book
- One Probe readme
- ActAdd book spawns if you do anything actadd related

Things that shouldn't:
- Evilcraft
- Abyssalcraft
- Roots natural arts book

Also we should turn off the on-spawn-get-this-book for the ones in the first list.  I think particularly for ActAdd and ID.

**Comment by gchpaco** [comment]
Totempedia should be in there too.

**Comment by esotericist** [comment]
have you worked with an akashic tome with that many things in it? does it get unwieldy?

**Comment by gchpaco** [comment]
Yes, I have, and it's a little awkward if you expected to hot swap between books in a hurry.  But I've never needed to do that, and I'm a bit confused as to why you would.

**Comment by esotericist** [comment]
I used to put my AM2 spellbook in akashic tome.

**Comment by gchpaco** [comment]
Yeah, that might be a bad idea with this much junk in one.

**Comment by esotericist** [comment]
I ended up having a lot of technical problems making this happen in a useful/reliable fashion.
Working around with Custom Starting Gear, having player start with an akashic tome with some stuff already in it.
