### ISSUE TITLE
Add more tools to the morphing tool whitelist

### ISSUE THREAD

**Issue by gchpaco** [gchpaco/minecraft_eso_paco#8]
- [x] Astral Sorcery resonating wand
- [x] Immersive Engineering hammer (bit awkward because it can be damaged, but still)
- [x] Embers hammer
- [x] Botania wand
- [x] Add the various TE mods as aliases to the alias list
- [x] Add McJty's various mods as aliases to the alias list

**Comment by gchpaco** [comment]
The config for the Thermal Foundation crescent hammer needs to make it appropriate for all the TE mods, too.

**Comment by esotericist** [comment]
> The config for the Thermal Foundation crescent hammer needs to make it appropriate for all the TE mods, too.

What does this mean?

**Comment by gchpaco** [comment]
Also missing; Botania wand seems to have changed names.

So the mod aliases section lists different mods that are considered equivalent for the purpose of Morph Tool.  For example, Thermal Dynamics and Thermal Expansion are equivalent, and so holding the TE wrench would still work for TD ducts.  In the most recent TE, that hammer got moved to Thermal Foundation, I think.

So we need to populate the mod aliases better, specifically for TE.

**Comment by esotericist** [comment]
do we know what happens to the morphing tool if a contained tool is destroyed from lack of durability?

**Comment by gchpaco** [comment]
I don't.

**Comment by esotericist** [comment]
Whee. science time.

**Comment by gchpaco** [comment]
Oh, also missing in mod aliases; McJty's various tech mods (RFtools control and xnet) need aliases.

**Comment by esotericist** [comment]
update your todo list? It'd be easier whenever I go to do these things to have a single list to look at

**Comment by esotericist** [comment]
When a tool in a morphing tool runs out of durability the whole thing evaporates. I'm voting to not include such tools.

**Comment by gchpaco** [comment]
Okay.

**Comment by esotericist** [comment]
It looks like the problem with botania is an issue with case. the config we have has capital letters in IDs which is no longer permitted.

Question for clarity: have you re-generated the config anytime recently, or is this one we've been carting around for multiple versions?

**Comment by gchpaco** [comment]
I have not regenerated it recently at all, no.

**Comment by esotericist** [comment]
Yeah, turns out we're carting around some old data for this and akashic.

**Comment by gchpaco** [comment]
Okay, that probably helps us out.

**Comment by esotericist** [comment]
Status:
* I can't get the embers hammer to not work, either in our original config, or the regenerated. I don't know what was going on with you there, but near as I can tell it's just working fine.
    * Notably: grandhammer is allowed. it probably shouldn't be, but fixing that would require blacklisting embers then whitelisting the basic hammer. Do we care enough?
* IE hammer added. It seems to work okay.
    * Set equivalences: both of immersivepetroleum and immersivetech to use immersiveengineering
* The COFH stuff was automatically handled upstream with regenerated config
* Same with botania wand
* Added resonating wand
* Set equivalences: all of rftoolsdim, rftoolscontrol, and xnet to use rftools

**Comment by gchpaco** [comment]
Okay, I think we can close this, then.

**Comment by esotericist** [comment]
Synced to dropbox.
