### ISSUE TITLE
Bedrock Ores config

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#9]
Our current configuration substantially reduces the frequency of bedrock ore veins from default (from a 0.5 incidence rate to 0.35), and slightly increases the vein size (from a base 2.0 scale to 3.0).

The consensus between the two of us seems to be that they show up at the right frequency (especially with the tendency for them to be hidden underneath the top layer of bedrock), but that they are far too voluminous.

Two factors currently at work: One, having any kind of baseline scalar makes it so that you can't just reference the default config for incidence rate. Two, the distance scaling algorithm makes it harder to make useful predictions given our tendency of picking out deployment sites after the world is generated.

The primary option I'm looking at is to set the base scale to 1.0, and set the distance scaling threshold to some implausibly high value, so that we can more readily predict the variance in node contents based on the raw configuration.

Adjacent to that, I was also wondering if we might want to play with the production rate. My belief is that we want these things to be a long-term return... but that doesn't necessarily have to mean high throughput on a per-miner basis. We do have the option of drastically increasing the time it takes per node extraction, which for high throughput would mean finding more nodes and getting a lot of miners working in parallel.

Also thinking strongly about disallowing hand mining of bedrock ores. A high mining speed hammer produces insane amounts of ore in just a few moments of standing at a vein and holding left mouse button. While convenient, it does trivialize actually *mining* in the normal sense.

Lastly: We probably want to revisit the energy costs at some point. Running a miner is, honestly, comparatively cheap next to the processing, especially with the current per-miner throughput. Of course, I think the energy expenditure is based on 'how much it takes per tick' rather than 'how much it takes per operation', so if anything, we might need to reduce the cost if we substantially decrease the throughput.

To sum: I think that the bedrock ores, while a fantastic concept, currently dominate things *far* too much, by the conjunction of 'plentiful' 'fast' and 'accessible'. We need to figure out which of these we're actually *wanting* and adjust the remainder to put normal mining (or even simple quarries) back in step.

**Comment by esotericist** [comment]
With our recent increase to the base range of Scannables, we might also get away with slightly (not extremely, just slightly) reducing the frequency of deposits.

**Comment by gchpaco** [comment]
I'm game for disallowing hand mining.  I know you floated a suggestion that the miner consume lots of power, and I don't think that's necessarily a great idea for a variety of reasons (namely it being more effective to ignore the bedrock stuff and just go mine, plus the difficulty of transmitting energy densely further encourages use of RFTools powercells and their power transmission mechanic).  I am game for knocking the size of the deposits down, like, by a third as a start.  I like the radius of the deposit where it is right now; can we just reduce the number of ores in any given block?

Also slowing the miner down is not unreasonable, although I think if it stops being "I found a tin deposit, I will now have ENOUGH TIN FOREVER" that may self moderate to some extent.

**Comment by esotericist** [comment]
We can easily scale the number of ores in a given block, and we can twiddle with both HEIGHT of deposits and thickness of bedrock; making it so more deposits can potentially be hidden and require Scannable to locate than already are the case.

I'm going to get the yields flattened (so they're the raw config values), and do some math on production rates so that I can be sure they don't get too expensive on the RF side after being slowed down.

After that, I'll report on the config for the ores, so that we'll know the shape and density of the deposits.

**Comment by esotericist** [comment]
Okay, some data.
We currently have 3 layers of bedrock; this can be increased if we want to 'hide' more deposits. More on that below.

The default time for a miner extraction is 100 ticks/5 seconds.
Miners are intended to operate partially off of normal furnace fuel, and by default get half as long burn time as the fuel normally would provide (so that charcoal, which burns for 1600 ticks, would only burn for 800 ticks. Coincidentally this is still 8 operations.)

The miner energy consumption is defined as the constant: BURN_TIME_PER_RF = 0.05
This means it takes 20 RF to get one tick of burntime, or 2000 RF for a single operation at the default rate. Except the same 50% efficiency applies, so it actually becomes 4,000 RF for a single operation with the default config.

The purpose of my intent in increasing extraction time is to encourage going parallel for getting throughput via bedrock ore deposits. If I increase the cycle time by four, that means you need to have found four deposits to get a similar throughput as previously.

The resource costs become: 1 charcoal/coal per 2 operations, or 16,000 RF per operation. Let's be realistic, neither of us is going to use solid fuel. So can we live with that RF cost?

Yields: It turns out that actual yield calculation is simpler for our purposes: the yield min/yield max is actually automatically divided amongst the individual actually extant blocks of the deposit regardless of the potential number of blocks, so there's no need to do complex math involving volume of the deposit to determine potential results. Easy for us.

[Here's the defaults for bedrock ores.](https://github.com/gchpaco/minecraft_eso_paco/wiki/Ore-Generation)

The gravel oil and redstone fluid entries are my doing, not defaults. All of the metals that in that table which show up from embers I specified, but I used the Thermal Expansion values for them from the default configs.

Hmin/Hmax: vertical span of the deposit. 2-4 if unspecified. Nothing specifies this as shipped, so it's not in the table.

With our bedrock thickness of 3, this means that if a deposit comes out a height of 2, it has a 50% chance of being not visible on the surface. If a deposit comes out 3 or 4, it simply uses the 3 layers we have (and we don't lose any yield this way if it rolls a higher height than we allow).

You may notice that completely absent any kind of scaling, many of these deposits have a maximum yield that simply do not justify the effort of setting up automation. I hate the distance scaling algorithm, but there's basically zero point setting up an actual mining station for, say, overworld quartz. Not for an entire 10 ore blocks. 

This is a big part of why my original desire was for 'incredibly huge deposits, but it takes forever to fully mine them'.

**Comment by esotericist** [comment]
Damn. I hoped tables would work here.

**Comment by esotericist** [comment]
Made a wiki page and linked that in the comment instead.

**Comment by esotericist** [comment]
Notably, my cooldown * 5 values for the fluid ores would not remotely make sense in the proposed 'everything goes slower' context, so that would obviously need revisiting.

**Comment by gchpaco** [comment]
yeah.  Hm.  The fluid stuff I'm inclined to make sure it's positive and then call it good, because if I remember anything from 1.4-1.6 it was that BC oil deposits don't last nearly you as long as you think they would.  There being large amounts of it just creates large problems when you invariably tap them out.  I'm not sure we really *have* big ticket constant RF items other than immersive petroleum and RFTools Dimensions now, but with the changes to the miners they may become one, and that's agreeable.

Our 3 layers of bedrock is fine by me, the actual occurrence rate and shape of the deposits works fine.  It's just the amount of sheer stuff in them that causes an issue.

**Comment by gchpaco** [comment]
Also you didn't seem to have a clear idea of a way forward with the ores, other than "less", which I concur with.  I've mooted starting by dividing the yield in 3 and we see how it goes.  Might need to be more.

**Comment by esotericist** [comment]
My current proposal:
Going ahead with the 20 seconds per extraction as a baseline, with iron ore as our reference ore. (16,000 RF per iron ore)

'Disable' the distance scaling (by way of setting the threshold stupid high), and setting the base scaling of deposits to 1.0.

Double the default minimum yield for the deposits (which is pretty low without any scaling whatsoever), but multiply the max yield by at least ~10 (which would put most of them well over 100 at maximum), giving a large range of potential size, but on average being somewhere between the two. might need to be higher, might need to bring up minimum for some ores.

(this would, for example, give us 360..2,250 per iron deposit, with a median deposit yield of ~1300ish. Meanwhile, gold would be 24..180, with a median yield of ~100)

Adjusting relative extraction rate ore tiers.
Coal, copper, tin, aluminum, glowstone, apatite: a little faster than iron ore. (16-18 seconds?)
gold, redstone, silver, lead, nickel, quartz: a little slower than iron ore. (25 seconds? that would be 20,000 RF per ore)
cobalt, ardite, resonating ore, diamond, emerald: a bit more slower than iron ore. (30 seconds? that would be 24,000 RF per ore)

Fluids will need to be reconsidered. oil ores need to be measurably energy-positive no matter where they end up, so that'll require math. resonant redstone ore can probably be at the same speed as vanilla redstone ore, since it's not primarily an energy producing substance.

**Comment by esotericist** [comment]
I'm by no means wedded to the relative rates. We can make the cooldown increases more extreme if we want, although if we do that, I'd be inclined to increase deposit sizes as well.

**Comment by esotericist** [comment]
side question: are there any new ores that need to be added to the bedrock ores tables?

**Comment by esotericist** [comment]
Nice thing: apparently since i last worked on this bedrock ores got a setting to control burn and power efficiency of miner separately, with the ability to disable either. Handy.

**Comment by esotericist** [comment]
Status: Canceled, we're removing bedrock ores (redundant with our current geolosys config and ore shrubs)
